---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: mysql-test
  name: mocomycnf
data:
  long_query_time: "0"
  innodb_log_file_size: "10M"

---
apiVersion: moco.cybozu.com/v1beta1
kind: MySQLCluster
metadata:
  namespace: mysql-test
  name: mysql
spec:
  replicas: 3
  mysqlConfigMapName: mocomycnf
  collectors:
  - engine_innodb_status
  - info_schema.innodb_metrics
  serviceTemplate : 
    spec : 
      type : NodePort
  podTemplate:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - mysql
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - mysql
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mysqld
        #image: harbor-dev.tcsa.tk/moco/cybozu/mysql:8.0.25
        image: quay.io/cybozu/mysql:8.0.25
        #resources:
        #  requests:
        #    cpu: "2"
        #    memory: "2Gi"
        #  limits:
        #    cpu: "2"
        #    memory: "4Gi"
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      annotations:
        #volume.beta.kubernetes.io/storage-class: "ceph-rbd"
        volume.beta.kubernetes.io/storage-class: "local-path"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
