---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: moco-demo
  name: mycnf
data:
  long_query_time: "0"
  innodb_log_file_size: "10M"

---
apiVersion: moco.cybozu.com/v1beta1
kind: MySQLCluster
metadata:
  namespace: moco-demo
  name: mysql
spec:
  replicas: 3
  mysqlConfigMapName: mycnf
  collectors:
  - engine_innodb_status
  - info_schema.innodb_metrics
  #serviceTemplate : 
  #  spec : 
  #    type : LoadBalancer
  podTemplate:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - mysql
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - mysql
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mysqld
        image: quay.io/cybozu/mysql:8.0.25
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      annotations:
        volume.beta.kubernetes.io/storage-class: "local-path"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
