---
apiVersion: v1
kind: Service
metadata:
  name: mocomysql
  namespace: moco-demo
  labels:
    app: shardingsphere-proxy
spec:
  ports:
  - name: shardingsphere-proxyout
    port: 3308
    protocol: TCP
    targetPort: 3308
  type: ClusterIP
  clusterIP: None
  selector:
    app: shardingsphere-proxy

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: shardingsphere-proxy
  name: shardingsphere-proxy
  namespace: moco-demo

spec:
  replicas: 1
  serviceName: shardingsphere-proxy
  selector:
    matchLabels:
      app: shardingsphere-proxy

  template:
    metadata:
      labels:
        app: shardingsphere-proxy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - shardingsphere-proxy
            topologyKey: kubernetes.io/hostname
      containers:
        - image: apache/sharding-proxy:5.0.0-beta1
          name: sharding-proxy
          imagePullPolicy: IfNotPresent
          #ports:
          #  - containerPort: 3308
          #    name: proxyport
          env:
            - name: PORT
              value: "3308"
          volumeMounts:
            - name: config-database-discovery
              mountPath: /opt/shardingsphere-proxy/conf/config-database-discovery.yaml
              subPath: config-database-discovery.yaml
            - name: config-encrypt
              mountPath: /opt/shardingsphere-proxy/conf/config-encrypt.yaml
              subPath: config-encrypt.yaml
            #config-readwrite-splitting
            #- name: config-readwrite-splitting
            #  mountPath: /opt/shardingsphere-proxy/conf/config-readwrite-splitting.yaml
            #  subPath: config-readwrite-splitting.yaml

            - name: config-data-simulator-dev
              mountPath: /opt/shardingsphere-proxy/conf/config-readwrite-splitting.yaml
              subPath: config-readwrite-splitting.yaml

            - name: config-open-platform-dev
              mountPath: /opt/shardingsphere-proxy/conf/config-readwrite-splitting2.yaml
              subPath: config-readwrite-splitting2.yaml
            #config-readwrite-splitting end
            - name: config-shadow
              mountPath: /opt/shardingsphere-proxy/conf/config-shadow.yaml
              subPath: config-shadow.yaml
            - name: config-sharding
              mountPath: /opt/shardingsphere-proxy/conf/config-sharding.yaml
              subPath: config-sharding.yaml
            - name: server
              mountPath: /opt/shardingsphere-proxy/conf/server.yaml
              subPath: server.yaml
      volumes:
        - name: config-database-discovery
          configMap:
            name: config-database-discovery
            items:
            - key: config-database-discovery.yaml
              path: config-database-discovery.yaml
        - name: config-encrypt
          configMap:
            name: config-encrypt
            items:
            - key: config-encrypt.yaml
              path: config-encrypt.yaml
        #config-readwrite-splitting
        #- name: config-readwrite-splitting
        #  configMap:
        #    name: config-readwrite-splitting
        #    items:
        #    - key: config-readwrite-splitting.yaml
        #      path: config-readwrite-splitting.yaml

        - name: config-data-simulator-dev
          configMap:
            name: config-data-simulator-dev
            items:
            - key: config-readwrite-splitting.yaml
              path: config-readwrite-splitting.yaml

        - name: config-open-platform-dev
          configMap:
            name: config-open-platform-dev
            items:
            - key: config-readwrite-splitting2.yaml
              path: config-readwrite-splitting2.yaml
        #config-readwrite-splitting end 
        - name: config-shadow
          configMap:
            name: config-shadow
            items:
            - key: config-shadow.yaml
              path: config-shadow.yaml
        - name: config-sharding
          configMap:
            name: config-sharding
            items:
            - key: config-sharding.yaml
              path: config-sharding.yaml
        - name: server
          configMap:
            name: server
            items:
            - key: server.yaml
              path: server.yaml
